"""initial identity schema

Revision ID: 0001_initial_identity_schema
Revises:
Create Date: 2026-08-08 20:59:50.801730
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial_identity_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "borrowers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("national_id", sa.String(length=100), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("phone_number_normalized", sa.String(length=32), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'deleted')", name=op.f("ck_borrowers_borrower_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrowers")),
        sa.UniqueConstraint("national_id", name=op.f("uq_borrowers_national_id")),
    )
    op.create_index(
        "ix_borrowers_phone_number_normalized",
        "borrowers",
        ["phone_number_normalized"],
        unique=False,
    )
    op.create_table(
        "business_settings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "business_name", sa.String(length=200), server_default="Lending Nelson", nullable=False
        ),
        sa.Column("currency_code", sa.String(length=3), server_default="PHP", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Manila", nullable=False),
        sa.Column("receipt_footer", sa.Text(), nullable=True),
        sa.Column(
            "default_monthly_estimate_rate", sa.Numeric(precision=12, scale=10), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "id = 'default'", name=op.f("ck_business_settings_business_setting_singleton")
        ),
        sa.CheckConstraint(
            "default_monthly_estimate_rate IS NULL OR default_monthly_estimate_rate >= 0",
            name=op.f("ck_business_settings_business_setting_nonnegative_estimate_rate"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_settings")),
    )
    op.bulk_insert(
        sa.table(
            "business_settings",
            sa.column("id", sa.String(length=32)),
            sa.column("business_name", sa.String(length=200)),
            sa.column("currency_code", sa.String(length=3)),
            sa.column("timezone", sa.String(length=64)),
            sa.column("default_monthly_estimate_rate", sa.Numeric(precision=12, scale=10)),
        ),
        [
            {
                "id": "default",
                "business_name": "Lending Nelson",
                "currency_code": "PHP",
                "timezone": "Asia/Manila",
                "default_monthly_estimate_rate": None,
            }
        ],
    )
    op.create_table(
        "owner_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owner_users")),
        sa.UniqueConstraint("username", name=op.f("uq_owner_users_username")),
    )
    op.create_index(
        "uq_owner_users_single_active",
        "owner_users",
        [sa.literal_column("(true)")],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_table(
        "borrower_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("borrower_id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("phone_number_normalized", sa.String(length=32), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=True),
        sa.Column("account_status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_status IN ('pending', 'approved', 'activated', 'suspended', 'disabled')",
            name=op.f("ck_borrower_accounts_borrower_account_status"),
        ),
        sa.ForeignKeyConstraint(
            ["borrower_id"],
            ["borrowers.id"],
            name=op.f("fk_borrower_accounts_borrower_id_borrowers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrower_accounts")),
        sa.UniqueConstraint("borrower_id", name=op.f("uq_borrower_accounts_borrower_id")),
        sa.UniqueConstraint(
            "phone_number_normalized", name=op.f("uq_borrower_accounts_phone_number_normalized")
        ),
    )
    op.create_table(
        "borrower_devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("borrower_account_id", sa.UUID(), nullable=False),
        sa.Column("device_identifier_hash", sa.String(length=128), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("push_token", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_trusted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["borrower_account_id"],
            ["borrower_accounts.id"],
            name=op.f("fk_borrower_devices_borrower_account_id_borrower_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrower_devices")),
        sa.UniqueConstraint(
            "borrower_account_id",
            "device_identifier_hash",
            name="uq_borrower_devices_account_device_hash",
        ),
        sa.UniqueConstraint("id", "borrower_account_id", name="uq_borrower_devices_id_account"),
    )
    op.create_index(
        "ix_borrower_devices_borrower_account_id",
        "borrower_devices",
        ["borrower_account_id"],
        unique=False,
    )
    op.create_table(
        "borrower_refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("borrower_account_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["borrower_account_id"],
            ["borrower_accounts.id"],
            name=op.f("fk_borrower_refresh_tokens_borrower_account_id_borrower_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["device_id", "borrower_account_id"],
            ["borrower_devices.id", "borrower_devices.borrower_account_id"],
            name="fk_borrower_refresh_tokens_device_account",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrower_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_borrower_refresh_tokens_token_hash")),
    )
    op.create_index(
        "ix_borrower_refresh_tokens_active_account_expires",
        "borrower_refresh_tokens",
        ["borrower_account_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "ix_borrower_refresh_tokens_borrower_account_id",
        "borrower_refresh_tokens",
        ["borrower_account_id"],
        unique=False,
    )
    op.create_index(
        "ix_borrower_refresh_tokens_device_id",
        "borrower_refresh_tokens",
        ["device_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_borrower_refresh_tokens_device_id", table_name="borrower_refresh_tokens")
    op.drop_index(
        "ix_borrower_refresh_tokens_borrower_account_id", table_name="borrower_refresh_tokens"
    )
    op.drop_index(
        "ix_borrower_refresh_tokens_active_account_expires",
        table_name="borrower_refresh_tokens",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("borrower_refresh_tokens")
    op.drop_index("ix_borrower_devices_borrower_account_id", table_name="borrower_devices")
    op.drop_table("borrower_devices")
    op.drop_table("borrower_accounts")
    op.drop_index(
        "uq_owner_users_single_active",
        table_name="owner_users",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("owner_users")
    op.drop_table("business_settings")
    op.drop_index("ix_borrowers_phone_number_normalized", table_name="borrowers")
    op.drop_table("borrowers")
    # ### end Alembic commands ###
